import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from pynput import keyboard
import threading
import time

class TeleopNode(Node):
        def __init__(self):
                    super().__init__('teleop_node')
                            self.publisher_ = self.create_publisher(Twist, '/cmd_vel', 10)
                                    self.current_twist = Twist()
                                            self.lock = threading.Lock()
                                                    self.active_keys = set()
                                                            self.running = True

                                                                    self.get_logger().info("Use W/A/S/D to move, Q to quit")

                                                                            # Start keyboard listener in a thread
                                                                                    listener = keyboard.Listener(
                                                                                                        on_press=self.key_pressed,
                                                                                                                    on_release=self.key_released
                                                                                                                            )
                                                                                            listener.start()

                                                                                                    # Start publishing loop in a thread
                                                                                                            threading.Thread(target=self.publish_loop, daemon=True).start()

                                                                                                                def key_pressed(self, key):
                                                                                                                            try:
                                                                                                                                            key_char = key.char.lower()
                                                                                                                                                    except AttributeError:
                                                                                                                                                                    return  # Special keys like shift, ctrl, etc.

                                                                                                                                                                        with self.lock:
                                                                                                                                                                                        self.active_keys.add(key_char)

                                                                                                                                                                                                if key_char == 'q':
                                                                                                                                                                                                                self.get_logger().info("Shutting down...")
                                                                                                                                                                                                                            self.running = False
                                                                                                                                                                                                                                        rclpy.shutdown()

                                                                                                                                                                                                                                            def key_released(self, key):
                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                        key_char = key.char.lower()
                                                                                                                                                                                                                                                                                except AttributeError:
                                                                                                                                                                                                                                                                                                return

                                                                                                                                                                                                                                                                                                    with self.lock:
                                                                                                                                                                                                                                                                                                                    if key_char in self.active_keys:
                                                                                                                                                                                                                                                                                                                                        self.active_keys.remove(key_char)

                                                                                                                                                                                                                                                                                                                                            def publish_loop(self):
                                                                                                                                                                                                                                                                                                                                                        rate = self.create_rate(20)  # 20 Hz
                                                                                                                                                                                                                                                                                                                                                                while rclpy.ok() and self.running:
                                                                                                                                                                                                                                                                                                                                                                                twist = Twist()

                                                                                                                                                                                                                                                                                                                                                                                            with self.lock:
                                                                                                                                                                                                                                                                                                                                                                                                                if 'w' in self.active_keys:
                                                                                                                                                                                                                                                                                                                                                                                                                                        twist.linear.x = 0.2
                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif 's' in self.active_keys:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                twist.linear.x = -0.2

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if 'a' in self.active_keys:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        twist.angular.z = 0.5
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif 'd' in self.active_keys:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                twist.angular.z = -0.5

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            self.publisher_.publish(twist)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rate.sleep()

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        def main(args=None):
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                rclpy.init(args=args)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    node = TeleopNode()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        rclpy.spin(node)

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if __name__ == '__main__':
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main()

